; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = esp-prog
debug_tool = esp-prog
debug_init_break = tbreak setup
build_type = debug
; upload_port = /dev/cu.usbserial-0001 ; Port for uploading without debugger
debug_speed = 10000
upload_speed = 921600
; debug_build_flags = -O0 -g -ggdb
board_build.f_cpu = 240000000
lib_ldf_mode = deep
lib_deps = 
	gyverlibs/GyverPortal@^3.6.6
